### ISSUE TITLE
Support for W3C ed25519-2020 verification key

### ISSUE THREAD

**Issue by victorjcarolino** [nuts-foundation/go-did#113]
Hello, I wonder if there will be support for the W3C ed25519-2020 verification keys as shown here soon if planned at all? What is the current state of planning for this support? 

W3C ed25519-2020 verification key specification: https://www.w3.org/community/reports/credentials/CG-FINAL-di-eddsa-2020-20220724/#dfn-ed25519verificationkey2020

**Comment by adrianmross** [comment]
This would be nuts (in a good way)! +1

**Comment by reinkrul** [comment]
Do you need it for DID documents, Verifiable Credentials or both?

If you need it for DID documents, it should be relatively easy to add support for it.

For Verifiable Credentials, I don't think there's anything in this library that prevents you from using it, as it doesn't create or verify signatures.

We're in the process of redesigning the Verifiable Credential part of this library to support upcoming new credential formats (e.g. SD-JWT) with more flexibility. Part of that exercise will also be introducing a separate library for Verifiable Credential handling (probably will be named something like `go-vc`). I expect this to land in about 2-3 months.

**Comment by m-rit** [comment]
@reinkrul, thanks for redirecting me to this issue!
I'll go ahead and raise a PR to add the ed25519-2020 support in the repo

**Comment by m-rit** [comment]
I've added the  support for did in this PR, but it looks like that the method is now deprecated as per  https://www.w3.org/TR/vc-di-eddsa/#ed25519verificationkey2020
As per the latest version, we should add support for Multikey

**Comment by reinkrul** [comment]
Note that this specification is still a draft, but chances are good the multikey requirement won't change. I think we'd welcome Multikey support, if it doesn't add too many/large dependencies.

@woutslakhorst ?

**Comment by woutslakhorst** [comment]
> Note that this specification is still a draft, but chances are good the multikey requirement won't change. I think we'd welcome Multikey support, if it doesn't add too many/large dependencies.
> 
> @woutslakhorst ?

Since it's derived from multibase, which has been along for quite some time, it's probably relative stable. Only side note I could find is that the IETFis going to standardise it. We won't deny any PR's for it, that's for sure.

**Comment by m-rit** [comment]
thank you for the inputs, I'll raise a PR for Multikey support then.

**Comment by reinkrul** [comment]
ed25519 (2020) VMs are now supported in 0.14.0
